logo: Bilder/Logo_FootballMap.jpg
title: FootballMap
description: Diese interaktive Fussball-Karte ist im Rahmen des Moduls 4230 GeoInformatik und Raumanalyse entstanden.
navigation: main
theme: jekyll-theme-minimal